version: "3.5"
services: 
    mariadb-glpi: 
        image: fametec/mariadb-glpi
        volumes: 
          - mariadb-glpi-volume:/var/www/mysql
        environment: 
          MYSQL_DATABASE: glpi
          MYSQL_USER: glpi 
          MYSQL_PASSWORD: glpi 
          MYSQL_RANDOM_ROOT_PASSWORD: 1 
        ports: 
          - 3307
        networks: 
          - backend
#
    glpi: 
        image: fametec/glpi
        volumes: 
          - glpi-volume:/var/www/html
        environment: 
          GLPI_LANG: pt_BR
          MARIADB_HOST: mariadb-glpi:3307
          MARIADB_DATABASE: glpi
          MARIADB_USER: glpi
          MARIADB_PASSWORD: glpi
          VERSION: "9.2.2"
        depends_on: 
          - mariadb-glpi
        ports: 
          - 30080:80
          - 30443:443
        networks: 
          - frontend
          - backend
#
    crond: 
        image: fametec/crond-glpi
        depends_on: 
          - glpi
          - mariadb-glpi
        environment:
          GLPI_LANG: pt_BR
          MARIADB_HOST: mariadb-glpi:3307
        volumes: 
          - glpi-volume:/var/www/html
        networks: 
          - backend
volumes: 
  glpi-volume:
  mariadb-glpi-volume: 
#
networks: 
  frontend: 
  backend: 
