version: "3"
services: 
    mariadb: 
        image: fametec/mariadb
        build: 
          context: ./mariadb/.
          dockerfile: Dockerfile
        volumes: 
          - /home/volume/mariadb:/var/lib/mysql
        ports: 
          - "3306"
    glpi: 
        image: fametec/apache
        build: 
          context: ./apache/.
          dockerfile: Dockerfile
       # environment: 
          #  MARIADB_PORT_3306_TCP_ADDR: mariadb
          #  MARIADB_ENV_MYSQL_USER: glpi
          #  MARIADB_ENV_MYSQL_PASSWORD: glpi
          #  MARIADB_ENV_MYSQL_DATABASE: glpi
        depends_on: 
          - mariadb
        links: 
          - mariadb
        ports: 
          - "443"
        volumes:
          - /home/volume/html:/var/www/html

    crond: 
        image: fametec/crond
        build: 
          context: ./crond/.
          dockerfile: Dockerfile
        depends_on: 
          - glpi
          - mariadb
        links: 
          - mariadb
        volumes: 
          - /home/volume/html:/var/www/html

